name: XNA Sprite Font Compile
on:
  workflow_dispatch:
    inputs:
      schema-path:
        description: "Path to spritefont schema file"
        required: true
        default: "SpriteFont0.spritefont"

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - name: Download Tool from github release latest using gh cli
        id: download-tool
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo revengenowstudio/XNAContentCompiler --pattern "XNAContentCompiler*.zip"
          # decompress zip file
          Expand-Archive -Path XNAContentCompiler*.zip -DestinationPath XNAContentCompiler
      # install msi from sdk/SharedFilesInstaller_File.msi
      - name: Install SharedFilesInstaller
        run: |
          $msiUrl = "https://github.com/revengenowstudio/XNAContentCompiler/raw/refs/heads/master/sdk/SharedFilesInstaller_File.msi"
          Invoke-WebRequest -Uri $msiUrl -OutFile "SharedFilesInstaller_File.msi"
          Start-Process msiexec.exe -ArgumentList '/i SharedFilesInstaller_File.msi /quiet /norestart' -Wait
      - name: Check some net4 files
        run: |
          $path = "C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll"
          if (Test-Path $path) {
            Write-Host "File exists: $path"
          } else {
            Write-Host "File does not exist: $path"
          }
          # calc sha256 of the file
          $sha256 = Get-FileHash -Path $path -Algorithm SHA256
          Write-Host "SHA256: $($sha256.Hash)"
      - name: Install Net4
        shell: pwsh
        run: |
          $downloadUrl = "https://download.microsoft.com/download/9/5/a/95a9616b-7a37-4af6-bc36-d6ea96c8daae/dotNetFx40_Full_x86_x64.exe"
          $output = "dotNetFx40_Full_x86_x64.exe"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $output
          Start-Process -FilePath $output -ArgumentList "/q /norestart" -Wait
          # .NET Framework 4.0 Targeting Pack
          choco install netfx-4.0.3-devpack --yes --force --execution-timeout=3600
          # show content of C:\Users\runneradmin\AppData\Local\Temp\chocolatey\netfx-4.0.3-devpack.log
          Get-Content -Path "C:\ProgramData\chocolatey\logs\chocolatey.log"
      - name: Download and install XNA 4.0
        run: |
          $xnaUrl = "https://download.microsoft.com/download/a/c/2/ac2c903b-e6e8-42c2-9fd7-bebac362a930/xnafx40_redist.msi"
          Invoke-WebRequest -Uri $xnaUrl -OutFile "xnafx40_redist.msi"
          Start-Process msiexec.exe -ArgumentList '/i xnafx40_redist.msi /quiet /norestart' -Wait
      - name: Download schema file
        id: schema-info
        shell: bash
        run: |
          url="${{ inputs.schema-path }}"
          # get last part of url as filename
          filename=$(basename "$url")
          # check wether url is a github url, and if so, convert to raw url
          # check whether url contains 'raw/refs'
          if [[ "$url" == *"github.com"* && "$url" == *"/raw/refs"* ]]; then
            # replace 'blob' with 'raw/refs/heads'
            url="${url/\/blob\//\/raw\/refs\/heads\/}"
          fi
          curl -L -o "$filename" "$url"
          echo "filename=$filename" >> $GITHUB_OUTPUT
      - name: Compile spritefont
        shell: pwsh
        run: |
          mkdir output
          ./XNAContentCompiler/XNA-CC-CLI.exe -i ./${{ steps.schema-info.outputs.filename }} -o ./output/ -c
          # check outputs, if empty then fail the step
          if ((Get-ChildItem -Path ./output/).Count -eq 0) {
            Write-Error "No output files generated"
            exit 1
          }
          Compress-Archive -Path ./output/* -DestinationPath SpriteFontOutput.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpriteFontOutput
          path: SpriteFontOutput.zip
          retention-days: 30
